### ISSUE TITLE
[Feature]-请求脚本支持对Reddit解锁的判断

### ISSUE THREAD

**Issue by ixxc** [lmc999/RegionRestrictionCheck#112]
rt，如果无法使用 https://www.reddit.com/ 网站的服务，会跳到如下阻止页面
![image](https://github.com/lmc999/RegionRestrictionCheck/assets/105781599/c084d62a-b92b-46a6-83da-633e38cbbbe1)

**Comment by betaxab** [comment]
添加 Reddit @lmc999 #116

**Comment by betaxab** [comment]
合并喽。可以关 issue 了。

**Comment by ixxc** [comment]
感谢大佬
