### ISSUE TITLE
日本区域 Niconico 检测不全

### ISSUE THREAD

**Issue by fireattack** [lmc999/RegionRestrictionCheck#124]
部分IP是可以观看niconico上的动画，但是对于锁日区的生放送还是没法播放。

例如这个： https://live.nicovideo.jp/watch/lv344942189
会显示

```
This program is not available
in your country or region.
```

**Comment by betaxab** [comment]
好，我尽快修了它。

**Comment by betaxab** [comment]
问一下这些不能看的直播从哪里找到的？

**Comment by fireattack** [comment]
我也不清楚怎么专门找，我是因为一直看这个节目知道他锁日区

只能说有不少标“官方”（“公式”）的直播会这样

**Comment by betaxab** [comment]
试试最新的可以了不：
`bash <(curl -L -s check.unlock.media) -M 4`

**Comment by fireattack** [comment]
可以很好，感谢~
