### ISSUE TITLE
FuboTV检测不再可靠

### ISSUE THREAD

**Issue by Arsierl** [lmc999/RegionRestrictionCheck#135]
https://api.fubo.tv/appconfig/v1/homepage?platform=web&client_version=1.78.2&nav=v0
此API返回内容已不再是可靠的判断方法
https://api.fubo.tv/appconfig/v3/location 中"network_allowed":false/true 测试后为可靠判断方法
并且FuboTV疑似在英国也有运营
{"postal":"wc2a 1aa","dma":"826044","country_code":"GBR","country_code2":"GB","country_name":"united kingdom","region_code":"CMD","connection_type":"broadband","asn":"197860","as_name":"haruka hosting ltd","ip_address":"89.213.1xx.1xx","display_name":"GBR","network_allowed":true}
如果"network_allowed":true建议添加地区"country_code2"返回

**Comment by lmc999** [comment]
谢谢PR，已合并
