### ISSUE TITLE
新增DAM檢測

### ISSUE THREAD

**Issue by ids93216** [lmc999/RegionRestrictionCheck#15]
你好 希望能夠新增日本DAM線上卡拉OK (**Karaoke@DAM**) 的檢測

判斷 http://cds1.clubdam.com/ 回傳狀態為200或403
希望能夠增加，謝謝了

**Comment by lmc999** [comment]
麻烦提供一下这个服务的网址(不是官网)，我添加前先要验证一下是不是你说的这个方法可以检测

**Comment by ids93216** [comment]
這個服務的網址是 https://www.clubdam.com/win10/sp/top.html

啟動時會驗證 http://cds1.clubdam.com/
視頻文件CDN https://cds1-clubdam.k56.ipcasting.jp/

前者無法加載則app無法啟動
後者無法加載則歌曲無法播放
我已經驗證過了，提供參考

**Comment by lmc999** [comment]
已经增加了，你测试一下

**Comment by ids93216** [comment]
![image](https://user-images.githubusercontent.com/4828920/131873969-68288548-4972-407e-983b-4b4d2c9ea223.png)

看起來沒問題，相當感謝

不過另外發現在台灣檢測台灣的幾個平台運行結果都是 Failed，應該是其他的bug

**Comment by lmc999** [comment]
看起来是有依赖没有安装好，你试试运行一下docker版，没问题的话就是依赖问题了
