### ISSUE TITLE
dmm检测不准确

### ISSUE THREAD

**Issue by jwstaceyOvO** [lmc999/RegionRestrictionCheck#20]
以dmit日本为例，检测结果yes，实际打开dmm.co.jp显示区域限制

**Comment by du5** [comment]
更换节点后不要刷新[not-available](https://special.dmm.co.jp/not-available-in-your-region/allservice/) 页面 建议重新打开[首页](https://www.dmm.co.jp/)测试

**Comment by lmc999** [comment]
> 以dmit日本为例，检测结果yes，实际打开dmm.co.jp显示区域限制

你测试的网页是Fanza的官网，可能跟dmm用的不是同一个IP库。

不打算支持Fanza这类网站的解锁检测
