### ISSUE TITLE
discoveryplus  的token 是否 失效？

### ISSUE THREAD

**Issue by KOP-XIAO** [lmc999/RegionRestrictionCheck#22]
你好，使用discoveryplus 的 验证时，始终时返回 400 code，  且 提示 token  invalid。
是否对应的token 失效呢？

**Comment by lmc999** [comment]
fixed https://github.com/lmc999/RegionRestrictionCheck/commit/89bfeb1fe787e7f0c3571bbcd1b6631c586495fd
