### ISSUE TITLE
HULU 显示 FAILED

### ISSUE THREAD

**Issue by OneHappyForever** [lmc999/RegionRestrictionCheck#24]
我用好几个原生IP的机器测试，都显示FAILED。其他的都可以解锁，可能是脚本出问题？

系统是CENTOS7, 64 bit

**Comment by lmc999** [comment]
hulu cookie不定時失效，已修復

**Comment by BrunuhVille** [comment]
> hulu cookie不定時失效，已修復

hulu现在好像都是Failed，测试了四五个机器
