### ISSUE TITLE
Dependency check missed nslookup

### ISSUE THREAD

**Issue by lhc1988** [lmc999/RegionRestrictionCheck#28]
The command 'nslookup' is not installed On some minimal installation OS. So I got an error while running this script. 

------
Netflix Preferred CDN:			->/dev/fd/63: line 1966: nslookup: command not found

**Comment by lmc999** [comment]
Please advise the exact OS where you encounter this problem?

**Comment by lhc1988** [comment]
Cent OS 8.0 minimal

**Comment by du5** [comment]
> Cent OS 8.0 minimal 

```bash
dnf -y install bind-utils
```
