### ISSUE TITLE
hbo的检测显示可以观看实际却不行

### ISSUE THREAD

**Issue by IanChen0713** [lmc999/RegionRestrictionCheck#29]
![image](https://user-images.githubusercontent.com/40349260/147844341-d9814c0b-1e44-4c8e-b9f6-1941835a6cdb.png)
流媒体检测中hbo通过测试
Netflix也通过测试而且是全解锁，但是我的ip是非原生ip没有用dns转发
查whois 地址是不符合的 但是Netflix能看 那为什么hbo不能看

**Comment by lmc999** [comment]
已在TG回复
