### ISSUE TITLE
Channel 4 检测结果不正确

### ISSUE THREAD

**Issue by HankChow** [lmc999/RegionRestrictionCheck#3]
Channel 4 检测结果是 Yes，但实际在 Channel 4 播放时还是显示仅在英国可用。

**Comment by lmc999** [comment]
请告知你的VPS商家，我看看有无办法复现

**Comment by HankChow** [comment]
> 请告知你的VPS商家，我看看有无办法复现

M247 英国 Manchester

**Comment by lmc999** [comment]
哪一家M247网络的VPS？总不至于直接跟M247购买VPS吧

**Comment by HankChow** [comment]
> 哪一家M247网络的VPS？总不至于直接跟M247购买VPS吧

onevps，但是现在似乎他们不提供 Manchester 的 vps 了

**Comment by Marcio2536** [comment]
這個不關腳本事, 是你設備時區的問題，改成倫敦時區(UTC+0)即可解決。
