### ISSUE TITLE
Netflix的测试结果不准确。

### ISSUE THREAD

**Issue by zhea55** [lmc999/RegionRestrictionCheck#33]
Netflix:				Originals Only

实际上我的VPS netflix都能看。

不知道为什么得出的结果是Originals Only

**Comment by lmc999** [comment]
大概因为你能看netflix但是看不了netflix上的版权剧

**Comment by zhea55** [comment]
> 大概因为你能看netflix但是看不了netflix上的版权剧

都能看。

**Comment by zhea55** [comment]
netflix自营的原创聚集没有多少。

很多非原创的。如果不能看的话。那老早就发现了。

**Comment by oneg1** [comment]
我的测试结果相反，脚本显示解锁 netflix，实测只能看自制剧

**Comment by sdshdv** [comment]
我也有这个问题，显示Netflix:Originals Only但是好像都能看，另外Originals Only和Only Homemade有啥具体区别吗

**Comment by YangZihao-lab** [comment]
Disney+检测结果也不准确，我的解开后检测结果还是no

**Comment by lmc999** [comment]
> Disney+检测结果也不准确，我的解开后检测结果还是no

请提供其他有效信息以供排查：Disney+账号区域，VPS区域，VPS提供商
