### ISSUE TITLE
fuboTV检测不准确

### ISSUE THREAD

**Issue by bbcbbk** [lmc999/RegionRestrictionCheck#46]
光检测首页没用,检测能过的VPS,登录进去之后看不了,说ip不符合要求
只要是美国ip都能通过首页, 登陆之后到https://www.fubo.tv/home 就提示ip不行了

**Comment by lmc999** [comment]
我没有fuboTV账号，如果需要登录才能检测的话我这边可能修复不了
或者你试试用能通过国主页但是不能通过https://www.fubo.tv/home的机器，在无痕模式下直接访问https://www.fubo.tv/home会不会出现geoblock的页面。

**Comment by bbcbbk** [comment]
> 我没有fuboTV账号，如果需要登录才能检测的话我这边可能修复不了 或者你试试用能通过国主页但是不能通过[https://www.fubo.tv/home的机器，在无痕模式下直接访问https://www.fubo.tv/home会不会出现geoblock的页面。](https://www.fubo.tv/home%E7%9A%84%E6%9C%BA%E5%99%A8%EF%BC%8C%E5%9C%A8%E6%97%A0%E7%97%95%E6%A8%A1%E5%BC%8F%E4%B8%8B%E7%9B%B4%E6%8E%A5%E8%AE%BF%E9%97%AEhttps://www.fubo.tv/home%E4%BC%9A%E4%B8%8D%E4%BC%9A%E5%87%BA%E7%8E%B0geoblock%E7%9A%84%E9%A1%B5%E9%9D%A2%E3%80%82)

估计是无解 我试了 直接访问 home也不跳geo,直接跳转到welcome页面

**Comment by betaxab** [comment]
尝试修复 @lmc999 #115

**Comment by betaxab** [comment]
> 目前的Fubo TV检测应该是正常的吧？

再合并了 #119 以后，应该就正常了。

**Comment by lmc999** [comment]
好的，谢谢！
