### ISSUE TITLE
[小bug] 参数选择

### ISSUE THREAD

**Issue by Polaris0112** [lmc999/RegionRestrictionCheck#47]
小问题，-E参数执行异常，check.sh第13行

现：
`while getopts ":I:M:E:X:" optname; do`
这样其实需要-E之后要带上参数，不然会进入兜底echo "Unknown error while processing options"

可以参考改成
`while getopts ":I:M:EX:" optname; do`
去掉E后冒号，就可以执行到指定的内容，不会影响其他参数

**Comment by lmc999** [comment]
谢谢反馈，我测试一下
