### ISSUE TITLE
disney+检测不准确

### ISSUE THREAD

**Issue by CXY037** [lmc999/RegionRestrictionCheck#48]
disney+检测 ipv4可以支持，实际使用v2ray分流 disney+依然不可以观看
vps位置 美国 vps提供商dmit ip地址DMIT (154.17.*.*)

**Comment by CXY037** [comment]
<img width="695" alt="image" src="https://user-images.githubusercontent.com/2595427/186552390-7d435cad-dbdd-4930-8c74-e07b48620fc4.png">

**Comment by CXY037** [comment]
<img width="829" alt="image" src="https://user-images.githubusercontent.com/2595427/186552437-1c2fc27a-db7a-4052-a7c5-075ae7f10f7f.png">

**Comment by CXY037** [comment]
可以提供vps测试

**Comment by lmc999** [comment]
建议你关闭ipv6再尝试，这样可以排除你的机器优先走IPv6访问disney+的这种可能性

**Comment by CXY037** [comment]
> 建议你关闭ipv6再尝试，这样可以排除你的机器优先走IPv6访问disney+的这种可能性

确实是关掉就可以了，感谢～我尝试怎么分流能修复～感谢
