### ISSUE TITLE
考虑增加类似 Roblox 这种游戏的检测吗

### ISSUE THREAD

**Issue by alexcc4** [lmc999/RegionRestrictionCheck#81]
[官网](https://mathsspot.com/play/roblox-corporation/5349/roblox)

**Comment by guaguaya66** [comment]
试试这个 `bash <(curl -L -s https://github.com/guaguaya66/RegionRestrictionCheck/raw/MathsSpot/check.sh)`

**Comment by guaguaya66** [comment]
> [官网](https://mathsspot.com/play/roblox-corporation/5349/roblox)

试试这个在北美和欧洲都添加了检测
`bash <(curl -L -s https://github.com/guaguaya66/RegionRestrictionCheck/raw/MathsSpot/check.sh)`

**Comment by alexcc4** [comment]
可以的。目前效果挺好的。
